### ISSUE TITLE
Issue with saving node register

### ISSUE THREAD

**Issue by olegogogo** [OpenCyphal/yakut#113]
Hello! I am trying to set registers at my CAN nodes. The values are written and work correctly. However, I cannot save them. The documentation says:

> When the configuration is deployed, we will probably need to restart the nodes for the changes to take effect:

So for example i was trying to publish baro temp data:

![image](https://github.com/user-attachments/assets/f81860ce-b646-4519-abce-b3fd12a731b5)

Probably "null" is not the answer I want to see. I was also trying factory reset as it is shown in [DSDL docs](https://github.com/OpenCyphal/public_regulated_data_types/blob/master/uavcan/node/435.ExecuteCommand.1.3.dsdl) but it gives me the same result shown in the screenshot below:

![image](https://github.com/user-attachments/assets/3db5bee9-b16b-4197-b8fd-69f38f8d03f6)

**Comment by pavel-kirienko** [comment]
Null is the correct response with -e. I don't know which Cyphal nodes you're using (why does it say "zubax"?) but they are clearly not working correctly. This is not a Yakut issue.
