### ISSUE TITLE
Install Instructions

### ISSUE THREAD

**Issue by SirJan18** [OpenCyphal/yakut#97]
In the installation instructions you are instructed to do the following: 
```
mkdir -p ~/.cyphal      # Ensure the directory actually exists.

# Add all namespaces from the public regulated data types repository:
wget https://github.com/OpenCyphal/public_regulated_data_types/archive/refs/heads/master.zip -O dsdl.zip
unzip dsdl.zip -d ~/.cyphal
mv -f ~/.cyphal/public_regulated_data_types*/* ~/.cyphal
# There will be some garbage left in the destination directory, but it's mostly harmless.

# Add vendor-specific namespaces the same way, if you need any:
wget https://github.com/Zubax/zubax_dsdl/archive/refs/heads/master.zip -O dsdl.zip
unzip dsdl.zip -d ~/.cyphal
mv -f ~/.cyphal/zubax_dsdl*/* ~/.cyphal
```

When following these directions the `./cyphal` folder contains the following folder `public_regulated_data_types-master`. After creating all the necessary environment variable attempting to run `yakut mon` an error message relating to the `uavcan` name space appears. This is due to the fact that the first fetched folder from the Github decompress to `public_regulated_data_types-master` instead of `public_regulated_data_types` which is what Yakut is looking for. I am requesting a change in the README installation instructions to reflect this.

**Comment by pavel-kirienko** [comment]
The instructions are correct. The mentioned directory is expected to be empty after the listed commands are executed; the DSDL namespace directories will be lifted directly to `~/.cyphal/` by the `mv` command. Please share the specific error message you're seeing along with the values of your environment variables.
